name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

permissions:
  contents: write

jobs:
  update-readme:
    name: Update WakaTime Coding Stats
    runs-on: ubuntu-latest

    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SECTION_NAME: waka
          SHOW_TITLE: true
          SHOW_TIME: true
          SHOW_TOTAL: true
          TIME_RANGE: last_7_days
          LANG_COUNT: 8
          CODE_LANG: txt
          COMMIT_MESSAGE: "chore: update waka coding stats"
